import { Router, type IRouter } from "express";
import adminHqSyncRouter from "./admin-hq-sync";
import cronHqSyncRouter from "./cron-hq-sync";
import healthRouter from "./health";
import registrationsRouter from "./registrations";
import adminAuthRouter from "./admin-auth";
import lookupRouter from "./lookup";
import adminSmsBackfillRouter from "./admin-sms-backfill";
const router: IRouter = Router();
router.use(adminHqSyncRouter);
router.use(cronHqSyncRouter);
router.use(healthRouter);
router.use(registrationsRouter);
router.use(adminAuthRouter);
router.use(lookupRouter);
router.use(adminSmsBackfillRouter);
export default router;
